### ISSUE TITLE
[chore] Weekly TODO List 

### ISSUE THREAD

**Issue by rnjstjdgh** [Everyone-s-delivery/Web#54]
# 2022-03-24 ~ 2022-03-31
### @rnjstjdgh 
-  페이징api 슬라이스 방식 다음페이지 유무 서버에서 판단해 boolean으로 내려주기(api의 명확성을 위해)
-  글 목록 api에서 덧글 안내려보내고 상세보기 했을때 주도록 변경하기

### @Psolmin 
- SNS 연동 API 사용방식 파악
- 서버 인증 방법이랑 연동 가능하도록 적용 가능 여부

### @manOfBackend 
- /posts 페이지 구현
---------------------------

**Comment by hyun-Bell** [comment]
### @manOfBackend 
- /posts 페이지 구현

**Comment by manOfBackend** [comment]
> ### @manOfBackend
> * /posts 페이지 구현

**Comment by rnjstjdgh** [comment]
@rnjstjdgh 

1.  현종이형 api 연동하면서 요청 사항 대응
2.  CI & CD dev 에 merge 시 aws에 배포되도록 변경
    * dev가 테스트 서버라고 생각한다.
3.  logger 강의 들으면서 도입할 만한 부분 있으면 커스텀 해서 도입해보기

### 수행내역
1.  API Server 설정 profile 을 통해 관리 & CI-CD dev branch로 변경
    * https://github.com/Everyone-s-delivery/Web/issues/63
2. api server logger 설정
    * https://github.com/Everyone-s-delivery/Web/issues/62

**Comment by hyun-Bell** [comment]
@manOfBackend 

1. posts 페이지 api 연동 (@rnjstjdgh)
2. kakao login api 연동 (@Psolmin)
3. 배포 페이지 접속 안 되는 현상 수정

**Comment by Psolmin** [comment]
@Psolmin 
   1. kakao login api 연동(@manOfBackend)
   2. kakao login 기존 서버 login 방식 적용(jwt)
   3. 인프런 강의 학습(스프링 입문)

**Comment by rnjstjdgh** [comment]
@rnjstjdgh 

1.  글 조회에 한에서는 토큰 없이 접근 가능하도록 `처리 완료`
2.  글 페이징이 지금 post method로 되어있는데 이거 get으로 변경`처리 완료`
    * RESTFULL한 방식을 최대한 지키자
    * get이면 기존 body로 보내던 json을 쿼리스트링으로
    * 계층구조 표현 가능한 방법 찾아서 적용

3.  페이징 api에서 offset & limit -> page & pageSize로 변경 `처리 완료`
    * api의 명확성 vs 유연성
    * 우리 서비스에서의 적합성

4.  X-AUTH-TOKEN 이름 변경`처리 완료`

5.  UI에서 글 목록으로 들어가면 jwt token 예외터지는거 수정

6.  JWT 토큰 보안을 위해 리프레시토큰 적용하기(리서치 필요)
7.  offset & limit 방식의 페이징 => Cursor 방식으로 변경?!

### 수행 내역
* 글 조회에 한에서는 토큰 없이 접근 가능하도록 &  X-AUTH-TOKEN 이름 변경
    * 관련 커밋: https://github.com/Everyone-s-delivery/Web/commit/1fd2046a60f5673563c4cf85c03d70057b68fc5c
* 글 페이징이 지금 post method로 되어있는데 이거 get으로 변경
* 페이징 api에서 offset & limit -> page & pageSize로 변경
    * 관련 커밋: https://github.com/Everyone-s-delivery/Web/commit/8a00444115b67512bca8a0958996e1f31e6de535

**Comment by Psolmin** [comment]
@Psolmin 
1. [x] 스프링 핵심 원리 - 기본편 50%
2. [x] kakao API - service 구현
3. [ ] kakao API 회원가입 - api 스펙

**Comment by rnjstjdgh** [comment]
@rnjstjdgh 
1.  JWT 토큰 기반 인증 강화 
    * refresh token 적용
    * 보안을 위해 서버에서 상태를 관리한다...? => Session 과 유사해 지는데?(좀 더 고민 필요)
    * 참고 자료: https://velog.io/@park2348190/JWT%EC%97%90%EC%84%9C-Refresh-Token%EC%9D%80-%EC%99%9C-%ED%95%84%EC%9A%94%ED%95%9C%EA%B0%80

2.  API 더미 데이터 생성
    * 이미지 비싼데....?

3.  덧글 사양?
    * 정해보자..

4.  페이징 사양 정리 후 반영
    * 요청 데이터
        * 시작 기간(`search.startDate`) & 끝 기간(`search.endDate`) & 정렬 키(`keyColumn`) & 정렬 방향(`orderBy`) 빼거나 디폴트 값 설정으로 처리하기(적어도 api에 필수 값으로 노출하지는 말자)
        * 무조건 글 등록 시간 기준 오름차순 + 기간 검색 안씀(커서로 할꺼니 부하 없음)
        * 날짜 값은 api 노출 시에는 long 값으로!
    * 응답 데이터
        * 이미지 url 추가하기
            * 우선 서버에서 모킹해서 제공하자
    * 커서 기반 페이징
        * idea => 인덱스를 걸고 where 로 바로 걸러서 가져온다.
        * 정렬 key => 등록 날짜 || 마지막 수정 일자
            * 시간 값 => unique & 정렬 가능 => 커서 기반 페이징 가능
        * 참고 자료: https://bbbicb.tistory.com/40 

5.  글 작성 api 사양 정리 후 반영
    * 이미지 등록 가능하도록


### 수행내역
*  글목록 페이징 변경: offset 기반 -> cursor 기반
    * 검색조건 변경 시 처음부터 요청
    * 정렬조건 변경 시 처음부터 요청
    * UI 가 커서를 관리하고 적절히 보내줘야함
*  DB 날짜 컬럼 타입 수정: datetime -> datetime(3)
*  DTO 의 날짜 타입 수정 : DB 에는 datetime으로, api 에는 long 으로
*  jpa batch size 설정을 통한 N+1 쿼리 문제 해결
